In [2]:
#Edge detection 
import cv2

In [2]:
!pip install cv2

ERROR: Could not find a version that satisfies the requirement cv2 (from versions: none)
ERROR: No matching distribution found for cv2

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
img = cv2.imread("dataset/photo1.jpeg")
img2 = cv2.imread("dataset/photo2.jpeg")
img3 = cv2.imread("dataset/photo3.jpeg")
cv2.imshow('Original',img)
cv2.waitKey(0)
cv2.imshow('Original',img2)
cv2.waitKey(0)
cv2.imshow('Original',img3)
cv2.waitKey(0)

-1

In [4]:
#image 1 gray scale and blur
img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
img_blur = cv2.GaussianBlur(img_gray,(3,3),0)

#image 2 gray scale and blur
img_gray2 = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
img_blur2 = cv2.GaussianBlur(img_gray2,(3,3),0)

#image 3 gray scale and blur
img_gray3 = cv2.cvtColor(img3,cv2.COLOR_BGR2GRAY)
img_blur3 = cv2.GaussianBlur(img_gray3,(3,3),0)

In [5]:
cv2.imshow('Gray',img_gray)
cv2.waitKey("q")

TypeError: Argument 'delay' is required to be an integer

In [5]:
cv2.imshow('Blur',img_blur)
cv2.waitKey(0)

-1

In [6]:
#Sobel edge detection image 1
sobelx = cv2.Sobel(src=img_blur, ddepth=cv2.CV_64F, dx=1, dy=0, ksize=5)
sobely = cv2.Sobel(src=img_blur, ddepth=cv2.CV_64F, dx=0, dy=1, ksize=5)
sobelxy = cv2.Sobel(src=img_blur, ddepth=cv2.CV_64F, dx=1, dy=1, ksize=5)

In [7]:
#Sobel edge detection image 2
sobelx2 = cv2.Sobel(src=img_blur2, ddepth=cv2.CV_64F, dx=1, dy=0, ksize=5)
sobely2 = cv2.Sobel(src=img_blur2, ddepth=cv2.CV_64F, dx=0, dy=1, ksize=5)
sobelxy2 = cv2.Sobel(src=img_blur2, ddepth=cv2.CV_64F, dx=1, dy=1, ksize=5)

In [8]:
#Sobel edge detection image 3
sobelx3 = cv2.Sobel(src=img_blur3, ddepth=cv2.CV_64F, dx=1, dy=0, ksize=5)
sobely3 = cv2.Sobel(src=img_blur3, ddepth=cv2.CV_64F, dx=0, dy=1, ksize=5)
sobelxy3 = cv2.Sobel(src=img_blur3, ddepth=cv2.CV_64F, dx=1, dy=1, ksize=5)

In [9]:
#Sobel X image 1
cv2.imshow('Sobel X', sobelx)
cv2.waitKey(0)

-1

In [10]:
#Sobel Y image 1
cv2.imshow('Sobel Y', sobely)
cv2.waitKey(0)

-1

In [11]:
#Sobel XY image 1 
cv2.imshow('Sobel X Y', sobelxy)
cv2.waitKey(0)

-1

In [12]:
#Sobel X image 2
cv2.imshow('Sobel X', sobelx2)
cv2.waitKey(0)

-1

In [13]:
#Sobel Y image 2
cv2.imshow('Sobel Y', sobely2)
cv2.waitKey(0)

-1

In [14]:
#Sobel XY image 2 
cv2.imshow('Sobel X Y', sobelxy2)
cv2.waitKey(0)

-1

In [15]:
#Sobel X image 3
cv2.imshow('Sobel X', sobelx3)
cv2.waitKey(0)

-1

In [16]:
#Sobel Y image 3
cv2.imshow('Sobel Y', sobely3)
cv2.waitKey(0)

-1

In [48]:
#Sobel XY image 2 
cv2.imshow('Sobel X Y', sobelxy3)
cv2.waitKey(0)

-1

In [50]:
#Canny edge detection
#image 1 edge detection
edges = cv2.Canny(image=img_blur, threshold1=100, threshold2=200)
#image 2 edge detection
edges2 = cv2.Canny(image=img_blur2, threshold1=100, threshold2=200)
#image 3 edge detection
edges3 = cv2.Canny(image=img_blur3, threshold1=100, threshold2=200)

In [20]:
#test
# edges = cv2.Canny(image=img, threshold1=100, threshold2=200)

In [51]:
#image 1 edge detection
cv2.imshow('Canny Edge Detection', edges)
cv2.waitKey(0)

-1

In [52]:
#image 2 edge detection
cv2.imshow('Canny Edge Detection', edges2)
cv2.waitKey(0)

-1

In [53]:
#image 3 edge detection
cv2.imshow('Canny Edge Detection', edges3)
cv2.waitKey(0)

-1

In [19]:
cv2.destroyAllWindows()

In [ ]:
#Reference = https://learnopencv.com/edge-detection-using-opencv/

In [1]:
#Corner detection 
import numpy as np
import cv2 as cv

In [2]:
img = cv.imread("dataset/photo1.jpeg")
img2 = cv.imread("dataset/photo2.jpeg")
img3 = cv.imread("dataset/photo3.jpeg")
gray = cv.cvtColor(img,cv.COLOR_BGR2GRAY)
gray2 = cv.cvtColor(img2,cv.COLOR_BGR2GRAY)
gray3 = cv.cvtColor(img3,cv.COLOR_BGR2GRAY)

In [3]:
gray

array([[195, 195, 195, ..., 142, 144, 146],
       [195, 195, 195, ..., 143, 145, 146],
       [195, 195, 195, ..., 144, 145, 146],
       ...,
       [ 56,  55,  53, ..., 114, 114, 114],
       [ 55,  53,  51, ..., 112, 112, 112],
       [ 54,  52,  50, ..., 111, 111, 111]], dtype=uint8)

In [4]:
# gray = np.float32(gray)
dst = cv.cornerHarris(gray,2,3,0.04)
dst2 = cv.cornerHarris(gray2,2,3,0.04)
dst3 = cv.cornerHarris(gray3,2,3,0.04)

In [5]:
dst = cv.dilate(dst,None)
img[dst>0.01*dst.max()]=[0,0,255]

dst2 = cv.dilate(dst2,None)
img2[dst2>0.01*dst2.max()]=[0,0,255]

dst3 = cv.dilate(dst3,None)
img3[dst3>0.01*dst3.max()]=[0,0,255]

In [6]:
cv.imshow('dst',img)
if cv.waitKey(0) & 0xff == 27:
    cv.destroyAllWindows()

In [7]:
cv.imshow('dst 2',img2)
if cv.waitKey(0) & 0xff == 27:
    cv.destroyAllWindows()

In [8]:
cv.imshow('dst 3',img3)
if cv.waitKey(0) & 0xff == 27:
    cv.destroyAllWindows()

In [ ]:
#Reference : https://docs.opencv.org/3.4/dc/d0d/tutorial_py_features_harris.html

In [9]:
#Line detection
import sys
import math
import cv2 as cv
import numpy as np

In [10]:
#image 1
src = cv.imread(cv.samples.findFile("dataset/photo1.jpeg"), cv.IMREAD_GRAYSCALE)
dst = cv.Canny(src, 50, 200, None, 3)

#image 2
src2 = cv.imread(cv.samples.findFile("dataset/photo2.jpeg"), cv.IMREAD_GRAYSCALE)
dst2 = cv.Canny(src2, 50, 200, None, 3)

#image 3
src3 = cv.imread(cv.samples.findFile("dataset/photo3.jpeg"), cv.IMREAD_GRAYSCALE)
dst3 = cv.Canny(src3, 50, 200, None, 3)

In [11]:
cdst = cv.cvtColor(dst, cv.COLOR_GRAY2BGR)
cdstP = np.copy(cdst)

cdst2 = cv.cvtColor(dst2, cv.COLOR_GRAY2BGR)
cdstP2 = np.copy(cdst2)

cdst3 = cv.cvtColor(dst3, cv.COLOR_GRAY2BGR)
cdstP3 = np.copy(cdst3)

In [12]:
lines = cv.HoughLines(dst, 1, np.pi / 180, 150, None, 0, 0)
lines2 = cv.HoughLines(dst2, 1, np.pi / 180, 150, None, 0, 0)
lines3 = cv.HoughLines(dst3, 1, np.pi / 180, 150, None, 0, 0)

In [13]:
lines

array([[[ 7.8700000e+02,  1.5358897e+00]],

       [[ 6.1000000e+02,  3.4906585e-02]],

       [[ 3.2900000e+02,  1.5533431e+00]],

       [[ 3.1400000e+02,  1.5707964e+00]],

       [[ 6.0500000e+02,  1.5707964e+00]],

       [[ 6.0100000e+02,  1.7453292e-02]],

       [[-7.9000000e+01,  2.9670596e+00]],

       [[ 6.6000000e+02,  1.0297443e+00]],

       [[-3.5500000e+02,  3.0892327e+00]]], dtype=float32)

In [14]:
if lines is not None:
        for i in range(0, len(lines)):
            rho = lines[i][0][0]
            theta = lines[i][0][1]
            a = math.cos(theta)
            b = math.sin(theta)
            x0 = a * rho
            y0 = b * rho
            pt1 = (int(x0 + 1000*(-b)), int(y0 + 1000*(a))) # rcosth - sinth, rsinth + costh
            pt2 = (int(x0 - 1000*(-b)), int(y0 - 1000*(a))) # rcosth + sinth, rsinth - costh
            cv.line(cdst, pt1, pt2, (0,0,255), 3, cv.LINE_AA)
            
linesP = cv.HoughLinesP(dst, 1, np.pi / 180, 50, None, 50, 10)

if linesP is not None:
        for i in range(0, len(linesP)):
            l = linesP[i][0]
            cv.line(cdstP, (l[0], l[1]), (l[2], l[3]), (0,0,255), 3, cv.LINE_AA)
            
cv.imshow("Source", src)
cv.imshow("Detected Lines (in red) - Standard Hough Line Transform", cdst)
cv.imshow("Detected Lines (in red) - Probabilistic Line Transform", cdstP)
cv.waitKey(0)

-1

In [15]:
if lines2 is not None:
        for i in range(0, len(lines2)):
            rho = lines2[i][0][0]
            theta = lines2[i][0][1]
            a = math.cos(theta)
            b = math.sin(theta)
            x0 = a * rho
            y0 = b * rho
            pt1 = (int(x0 + 1000*(-b)), int(y0 + 1000*(a)))
            pt2 = (int(x0 - 1000*(-b)), int(y0 - 1000*(a)))
            cv.line(cdst2, pt1, pt2, (0,0,255), 3, cv.LINE_AA)
            
linesP = cv.HoughLinesP(dst2, 1, np.pi / 180, 50, None, 50, 10)

if linesP is not None:
        for i in range(0, len(linesP)):
            l = linesP[i][0]
            cv.line(cdstP2, (l[0], l[1]), (l[2], l[3]), (0,0,255), 3, cv.LINE_AA)
            
cv.imshow("Source", src2)
cv.imshow("Detected Lines (in red) - Standard Hough Line Transform", cdst2)
cv.imshow("Detected Lines (in red) - Probabilistic Line Transform", cdstP2)
cv.waitKey(0)

-1

In [16]:
linesP

array([[[ 276, 1161,  932, 1264]],

       [[ 153,  715,  545,  652]],

       [[ 139,  773,  550,  693]],

       ...,

       [[ 546,  361,  551,  289]],

       [[ 249,  779,  326,  762]],

       [[ 609,  239,  659,  241]]], dtype=int32)

In [17]:
if lines3 is not None:
        for i in range(0, len(lines3)):
            rho = lines3[i][0][0]
            theta = lines3[i][0][1]
            a = math.cos(theta)
            b = math.sin(theta)
            x0 = a * rho
            y0 = b * rho
            pt1 = (int(x0 + 1000*(-b)), int(y0 + 1000*(a)))
            pt2 = (int(x0 - 1000*(-b)), int(y0 - 1000*(a)))
            cv.line(cdst3, pt1, pt2, (0,0,255), 3, cv.LINE_AA)
            
linesP = cv.HoughLinesP(dst3, 1, np.pi / 180, 50, None, 50, 10)

if linesP is not None:
        for i in range(0, len(linesP)):
            l = linesP[i][0]
            cv.line(cdstP3, (l[0], l[1]), (l[2], l[3]), (0,0,255), 3, cv.LINE_AA)
            
cv.imshow("Source", src3)
cv.imshow("Detected Lines (in red) - Standard Hough Line Transform", cdst3)
cv.imshow("Detected Lines (in red) - Probabilistic Line Transform", cdstP3)
cv.waitKey(0)

-1

In [ ]:
#reference: https://docs.opencv.org/3.4/d9/db0/tutorial_hough_lines.html

In [18]:
#Gabor filter
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [30]:
img = cv2.imread("dataset/photo3.jpeg")
cv2.imshow("Source",img)
cv2.waitKey(0)

-1

In [31]:
def build_filters(_lambda,_orientation):
    filters = []
    ksize = 31
#     for theta in np.arange(0, np.pi, np.pi / 16):
#         kern = cv2.getGaborKernel((ksize, ksize), 4.0, theta, 10.0, 0.5, 0, ktype=cv2.CV_32F)
    theta = np.radians(_orientation)
    kern = cv2.getGaborKernel((ksize, ksize), 4.0, theta, _lambda, 0.5, 0, ktype=cv2.CV_32F)
    kern /= 1.5*kern.sum()
    filters.append(kern)
    return filters

In [32]:
def process(img, filters):
    accum = np.zeros_like(img)
    for kern in filters:
        fimg = cv2.filter2D(img, cv2.CV_8UC3, kern)
        np.maximum(accum, fimg, accum)
    return accum

In [40]:
filters20_0 = build_filters(20,0)
res1 = process(img, filters20_0)
cv2.imshow('result wavelength=20 , orientation=0', res1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [39]:
filters80_0 = build_filters(80,0)
res1 = process(img, filters80_0)
cv2.imshow('result wavelength=80 , orientation=0', res1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [37]:
filters30_90 = build_filters(30,90)
res1 = process(img, filters30_90)
cv2.imshow('result wavelength=30 , orientation=90', res1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [41]:
filters10_150 = build_filters(10,150)
res1 = process(img, filters10_150)
cv2.imshow('result wavelength=10 , orientation=150', res1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#reference https://cvtuts.wordpress.com/2014/04/27/gabor-filters-a-practical-overview/

In [28]:
# !pip install pywt
!pip install PyWavelets

     ---------------------------------------- 4.2/4.2 MB 3.3 MB/s eta 0:00:00



[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
#discrete wavelet transform
import cv2
import numpy as np
import pywt

In [2]:
img = cv2.imread("dataset/photo1.jpeg")
img

array([[[209, 203, 174],
        [209, 203, 174],
        [209, 203, 174],
        ...,
        [161, 149, 121],
        [163, 151, 123],
        [165, 153, 125]],

       [[209, 203, 174],
        [209, 203, 174],
        [209, 203, 174],
        ...,
        [162, 150, 122],
        [164, 152, 124],
        [165, 153, 125]],

       [[209, 203, 174],
        [209, 203, 174],
        [209, 203, 174],
        ...,
        [163, 151, 123],
        [164, 152, 124],
        [165, 153, 125]],

       ...,

       [[ 26,  40,  98],
        [ 25,  39,  97],
        [ 23,  37,  95],
        ...,
        [ 64, 101, 157],
        [ 64, 101, 157],
        [ 64, 101, 157]],

       [[ 25,  39,  97],
        [ 23,  37,  95],
        [ 21,  35,  93],
        ...,
        [ 62,  99, 155],
        [ 62,  99, 155],
        [ 62,  99, 155]],

       [[ 24,  38,  96],
        [ 22,  36,  94],
        [ 20,  34,  92],
        ...,
        [ 61,  98, 154],
        [ 61,  98, 154],
        [ 61,  98, 154]]

In [3]:
data = pywt.dwt(img, 'db1')

In [4]:
type(data)

tuple

In [5]:
data

(array([[[291.32799385, 246.07315985],
         [291.32799385, 246.07315985],
         [291.32799385, 246.07315985],
         ...,
         [219.20310217, 171.11984105],
         [222.03152929, 173.94826817],
         [224.85995642, 176.7766953 ]],
 
        [[291.32799385, 246.07315985],
         [291.32799385, 246.07315985],
         [291.32799385, 246.07315985],
         ...,
         [220.61731573, 172.53405461],
         [223.44574285, 175.36248173],
         [224.85995642, 176.7766953 ]],
 
        [[291.32799385, 246.07315985],
         [291.32799385, 246.07315985],
         [291.32799385, 246.07315985],
         ...,
         [222.03152929, 173.94826817],
         [223.44574285, 175.36248173],
         [224.85995642, 176.7766953 ]],
 
        ...,
 
        [[ 46.66904756, 138.59292911],
         [ 45.254834  , 137.17871555],
         [ 42.42640687, 134.35028843],
         ...,
         [116.6726189 , 222.03152929],
         [116.6726189 , 222.03152929],
         [116.6726189 ,

In [36]:
from PIL import Image
Image.fromarray(data)

AttributeError: 'tuple' object has no attribute '__array_interface__'